"use strict";
exports.__esModule = true;
var persona_1 = require("./persona");
var direccion_1 = require("./direccion");
var mail_1 = require("./mail");
var telefono_1 = require("./telefono");
var Domicilio01Valeria = new direccion_1.Direccion("Calle Maestro Arrieta", 1, 2, "B", 12006, "Castellón de la Plana", "Castellón");
var Domicilio02Valeria = new direccion_1.Direccion("Calle Obispo", 3, 2, "C", 12005, "Castellón de la Plana", "Castellón");
var mailValeria = new mail_1.Mail("personal", "valeria@gmail.com");
var telefonoFijoValeria = new telefono_1.Telefono("fijo", 964552233);
var telefonoMovilValeria = new telefono_1.Telefono("movil", 672890979);
var datosValeria = new persona_1.Persona('Valeria', 'Márquez García', 23, '25012548V', new Date(2000, 8, 15), 'azul', 'mujer', [Domicilio01Valeria, Domicilio02Valeria], [mailValeria], [telefonoFijoValeria, telefonoMovilValeria], "El domicilio habitual es el 01");
var Domicilio01Luis = new direccion_1.Direccion("Calle Buendía", 12, 1, "A", 50005, "Almassora", "Castellón");
var Domicilio02Luis = new direccion_1.Direccion("Calle Canti", 88, 3, "C", 12001, "Vila-real", "Castellón");
var mailPersonalLuis = new mail_1.Mail("personal", "luis@hotmail.com");
var mailTrabajoLuis = new mail_1.Mail("personal", "luis@empresa.com");
var telefonoFijoLuis = new telefono_1.Telefono("fijo", 964558877);
var telefonoMovilLuisPersonal = new telefono_1.Telefono("movil", 633251489);
var datosLuis = new persona_1.Persona('Luis', 'María Fernández', 25, '15245789M', new Date(1998, 11, 11), 'verde', 'hombre', [Domicilio01Luis, Domicilio02Luis], [mailPersonalLuis, mailTrabajoLuis], [telefonoFijoLuis, telefonoMovilLuisPersonal], "Vive en el domicilio 02");
var Domicilio01Silvia = new direccion_1.Direccion("Calle Duquesa Vanesa", 33, 5, "A", 12005, "Castellón de la Plana", "Castellón");
var Domicilio02Silvia = new direccion_1.Direccion("Calle Avefría", 15, 1, "B", 12008, "Castellón de la Plana", "Castellón");
var mailPersonalSilvia = new mail_1.Mail("personal", "Silvia@gmail.com");
var mailTrabajoSilvia = new mail_1.Mail("trabajo", "silvia@trabaja.com");
var telefonoFijoSilvia = new telefono_1.Telefono("fijo", 964552233);
var telefonoMovilSilvia = new telefono_1.Telefono("movil", 666951753);
var datosSilvia = new persona_1.Persona('Silvia', 'Alonso Rodríguez', 34, '52147896C', new Date(1988, 5, 25), 'rosa', 'mujer', [Domicilio01Silvia, Domicilio02Silvia], [mailPersonalSilvia, mailTrabajoSilvia], [telefonoFijoSilvia, telefonoMovilSilvia], "Vive en el domicilio 01");
console.log("Contactos antes del cambio:");
console.log(datosValeria);
console.log(datosLuis);
console.log(datosSilvia);
var agenda = new Array(datosValeria, datosLuis, datosSilvia);
var dniABuscar = "52147896C";
var personaAEditar = agenda.find(function (persona) { return persona.dni === dniABuscar; });
var nuevaDireccion = new direccion_1.Direccion("Calle en Medio", 6, 4, "B", 12005, "Vinaròs", "Castellón");
var nuevoMail = new mail_1.Mail("personal", "hola@webmail .org");
var nuevoTelefono = new telefono_1.Telefono("móvil", 652349857);
personaAEditar.agregarNuevaDireccion(nuevaDireccion);
personaAEditar.agregarNuevoMail(nuevoMail);
personaAEditar.agregarNuevoTelefono(nuevoTelefono);
console.log("Contactos después del cambio:");
console.log(datosValeria);
console.log(datosLuis);
console.log(datosSilvia);
